baseURL = "https://beckgoodman.netlify.app/"
languageCode = "en-us"
paginate = 6
summaryLength = "10"
theme = "influencer-hugo"
title = "Beck Goodman"
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 3
[[menu.main]]
URL = "review"
name = "Reviews"
weight = 2
[[menu.main]]
URL = "book"
name = "About"
weight = 1
[params]
author = "Themefisher"
copyright = "Copyright &copy; 2019 [GetHugoThemes](https://gethugothemes.com) All Rights Reserved"
description = "This is meta description"
googleAnalitycsID = ""
home = "Home"
logo = ""
[params.footer]
content = "Each theme featured at the Bootstrap marketplace has been reviewed by Bootstrap's creators.Lorem ipsum dolor sit amet, consectetur adipisicing elit."
[params.navButton]
enable = true
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/magnific-popup/magnific-popup.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.share]]
icon = "ti-facebook"
link = "#"
title = "facebook"
[[params.share]]
icon = "ti-twitter-alt"
link = "#"
title = "twitter"
[[params.share]]
icon = "ti-linkedin"
link = "#"
title = "linkedin"
[[params.share]]
icon = "ti-github"
link = "#"
title = "github"
